tasks:
  - init: |
      cd .devcontainer && docker-compose pull && docker-compose build && cd -
  - command: |
      cd .devcontainer && docker-compose -f docker-compose.yml -f docker-compose.gitpod.yml up -d && docker-compose -f docker-compose.yml -f docker-compose.gitpod.yml exec web sh /var/www/html/httpdocs/.devcontainer/postCreateCommand.sh
    
ports:
  - port: 3306
    onOpen: ignore
    visibility: private
  - port: 42535
    onOpen: open-preview
    visibility: private
  - port: 9010
    onOpen: ignore
    visibility: private
  - port: 8025
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - felixfbecker.php-debug
    - felixfbecker.php-intellisense
    - mrmlnc.vscode-apache
    - mtxr.sqltools
    - mtxr.sqltools-driver-mysql
    - mblode.twig-language-2
    - mblode.twig-language
    - bmewburn.vscode-intelephense-client
    - formulahendry.code-runner
    - deibit.devdocs
    - eamodio.gitlens